"""initial_clean_schema

Revision ID: 256a23c3cec4
Revises: 
Create Date: 2025-11-29 22:19:15.898232

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '256a23c3cec4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único de la categoría'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo: necesidades, gustos, ahorros'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo de la categoría'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción detallada de la categoría'),
    sa.Column('icono', sa.String(length=10), nullable=False, comment='Emoji o icono para la categoría'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_nombre'), 'categories', ['nombre'], unique=False)
    op.create_index(op.f('ix_categories_tipo'), 'categories', ['tipo'], unique=True)
    op.create_table('exchange_rate_cache',
    sa.Column('date', sa.Date(), nullable=False, comment='Fecha del tipo de cambio (YYYY-MM-DD)'),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False, comment='Tipo de cambio USD a CRC (ej: 530.50)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Fuente: hacienda_cr, exchangerate_api, default'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint("source IN ('hacienda_cr', 'exchangerate_api', 'default')", name='check_valid_source'),
    sa.CheckConstraint('rate > 0', name='check_rate_positive'),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=100), nullable=False, comment='Nombre limpio y unificado'),
    sa.Column('categoria_principal', sa.String(length=50), nullable=False, comment='Categoría principal (ej: Restaurante, Supermercado)'),
    sa.Column('subcategoria', sa.String(length=50), nullable=True, comment='Subcategoría (ej: Comida Rápida, Farmacia)'),
    sa.Column('tipo_negocio', sa.String(length=30), nullable=False, comment='Tipo: food_service, retail, gas_station, healthcare, entertainment, etc.'),
    sa.Column('que_vende', sa.Text(), nullable=True, comment='Descripción de productos/servicios'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL del logo del comercio'),
    sa.Column('color_brand', sa.String(length=7), nullable=True, comment='Color de marca en hex (ej: #FF5733)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_categoria_principal'), 'merchants', ['categoria_principal'], unique=False)
    op.create_index(op.f('ix_merchants_nombre_normalizado'), 'merchants', ['nombre_normalizado'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_outlook', sa.String(length=255), nullable=False, comment='Email de Outlook donde se reciben los correos bancarios'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del perfil (ej: Personal, Negocio, Mamá)'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción opcional del perfil'),
    sa.Column('icono', sa.String(length=10), nullable=True, comment='Icono emoji del perfil'),
    sa.Column('es_activo', sa.Boolean(), nullable=False, comment='Si este es el perfil actualmente activo en el dashboard'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Si el perfil está habilitado (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email_outlook'), 'profiles', ['email_outlook'], unique=True)
    op.create_index(op.f('ix_profiles_es_activo'), 'profiles', ['es_activo'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único de la tarjeta'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil al que pertenece esta tarjeta'),
    sa.Column('ultimos_4_digitos', sa.String(length=4), nullable=False, comment='Últimos 4 dígitos de la tarjeta (ej: 3640)'),
    sa.Column('tipo', sa.String(length=10), nullable=False, comment='Tipo: debito o credito'),
    sa.Column('banco', sa.String(length=50), nullable=False, comment='Banco emisor: bac, popular'),
    sa.Column('marca', sa.String(length=20), nullable=True, comment='Marca: visa, mastercard, etc.'),
    sa.Column('limite_credito', sa.Numeric(precision=15, scale=2), nullable=True, comment='Límite de crédito en colones (solo para tarjetas de crédito)'),
    sa.Column('fecha_corte', sa.Integer(), nullable=True, comment='Día del mes de corte (1-31)'),
    sa.Column('fecha_vencimiento', sa.Integer(), nullable=True, comment='Día del mes de vencimiento (1-31)'),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Saldo actual de la tarjeta de crédito en colones'),
    sa.Column('interest_rate_annual', sa.Numeric(precision=5, scale=2), nullable=True, comment='Tasa de interés anual en % (ej: 52.00 para 52%)'),
    sa.Column('minimum_payment_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje de pago mínimo (ej: 2.50 para 2.5%)'),
    sa.Column('card_expiration_date', sa.Date(), nullable=True, comment='Fecha de vencimiento del plástico (mes/año)'),
    sa.Column('alias', sa.String(length=100), nullable=True, comment="Alias personalizado (ej: 'Tarjeta principal', 'Débito BAC')"),
    sa.Column('activa', sa.Boolean(), nullable=False, comment='Si la tarjeta está activa'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de registro de la tarjeta'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint('fecha_corte IS NULL OR (fecha_corte >= 1 AND fecha_corte <= 31)', name='check_card_fecha_corte_valid'),
    sa.CheckConstraint('fecha_vencimiento IS NULL OR (fecha_vencimiento >= 1 AND fecha_vencimiento <= 31)', name='check_card_fecha_venc_valid'),
    sa.CheckConstraint('limite_credito IS NULL OR limite_credito > 0', name='check_card_limite_positive'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_activa'), 'cards', ['activa'], unique=False)
    op.create_index(op.f('ix_cards_deleted_at'), 'cards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cards_profile_id'), 'cards', ['profile_id'], unique=False)
    op.create_index('ix_cards_profile_tipo', 'cards', ['profile_id', 'tipo'], unique=False)
    op.create_index(op.f('ix_cards_tipo'), 'cards', ['tipo'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único del ingreso'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil al que pertenece este ingreso'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo de ingreso: salario, freelance, venta, etc.'),
    sa.Column('descripcion', sa.String(length=255), nullable=False, comment="Descripción del ingreso (ej: 'Salario Noviembre 2025', 'Venta PS5')"),
    sa.Column('monto_original', sa.Numeric(precision=15, scale=2), nullable=False, comment='Monto en la moneda original'),
    sa.Column('moneda_original', sa.String(length=3), nullable=False, comment='Moneda: CRC o USD'),
    sa.Column('monto_crc', sa.Numeric(precision=15, scale=2), nullable=False, comment='Monto convertido a colones'),
    sa.Column('tipo_cambio_usado', sa.Numeric(precision=10, scale=4), nullable=True, comment='Tipo de cambio si se hizo conversión'),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha en que se recibió el ingreso'),
    sa.Column('es_recurrente', sa.Boolean(), nullable=False, comment='Si es un ingreso recurrente (ej: salario mensual)'),
    sa.Column('frecuencia', sa.String(length=15), nullable=True, comment='Frecuencia si es recurrente: mensual, quincenal, etc.'),
    sa.Column('proximo_ingreso_esperado', sa.Date(), nullable=True, comment='Fecha esperada del próximo ingreso (si es recurrente)'),
    sa.Column('email_id', sa.String(length=255), nullable=True, comment='ID del correo de origen (si aplica)'),
    sa.Column('confirmado', sa.Boolean(), nullable=False, comment='Si el ingreso está confirmado'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('contexto', sa.Text(), nullable=True, comment="Contexto del ingreso en lenguaje natural (ej: 'Mamá me pasó para comprar carne')"),
    sa.Column('tipo_especial', sa.String(length=50), nullable=True, comment='Tipo especial de movimiento (dinero_ajeno, intermediaria, ajuste_inicial, etc.)'),
    sa.Column('excluir_de_presupuesto', sa.Boolean(), nullable=False, comment='Si se debe excluir del cálculo de presupuesto mensual 50/30/20'),
    sa.Column('es_dinero_ajeno', sa.Boolean(), nullable=False, comment='Si el dinero es de otra persona (no es ingreso real tuyo)'),
    sa.Column('requiere_desglose', sa.Boolean(), nullable=False, comment='Si este ingreso se desglosó en múltiples gastos'),
    sa.Column('monto_usado', sa.Numeric(precision=15, scale=2), nullable=True, comment='Monto que realmente usaste/gastaste de este ingreso'),
    sa.Column('monto_sobrante', sa.Numeric(precision=15, scale=2), nullable=True, comment='Monto que te sobraste/quedaste de este ingreso (va a tu patrimonio)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint('monto_crc > 0', name='check_income_monto_positive'),
    sa.CheckConstraint('monto_original > 0', name='check_income_original_positive'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_confirmado'), 'incomes', ['confirmado'], unique=False)
    op.create_index(op.f('ix_incomes_deleted_at'), 'incomes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_incomes_email_id'), 'incomes', ['email_id'], unique=True)
    op.create_index(op.f('ix_incomes_es_recurrente'), 'incomes', ['es_recurrente'], unique=False)
    op.create_index(op.f('ix_incomes_excluir_de_presupuesto'), 'incomes', ['excluir_de_presupuesto'], unique=False)
    op.create_index(op.f('ix_incomes_fecha'), 'incomes', ['fecha'], unique=False)
    op.create_index(op.f('ix_incomes_monto_crc'), 'incomes', ['monto_crc'], unique=False)
    op.create_index('ix_incomes_profile_fecha', 'incomes', ['profile_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_incomes_profile_id'), 'incomes', ['profile_id'], unique=False)
    op.create_index('ix_incomes_profile_tipo', 'incomes', ['profile_id', 'tipo'], unique=False)
    op.create_index(op.f('ix_incomes_tipo'), 'incomes', ['tipo'], unique=False)
    op.create_index(op.f('ix_incomes_tipo_especial'), 'incomes', ['tipo_especial'], unique=False)
    op.create_table('merchant_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('nombre_raw', sa.String(length=200), nullable=False, comment='Nombre exacto del correo bancario'),
    sa.Column('ciudad', sa.String(length=100), nullable=True, comment='Ciudad donde está el local'),
    sa.Column('pais', sa.String(length=50), nullable=False, comment='País'),
    sa.Column('ubicacion_descriptiva', sa.String(length=200), nullable=True, comment='Descripción de ubicación (ej: Momentum Pinares, Mall San Pedro)'),
    sa.Column('confianza_match', sa.Numeric(precision=3, scale=2), nullable=False, comment='Confianza del match (0.0 - 1.0). 1.0 = manual/confirmado'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merchant_variants_merchant_ciudad', 'merchant_variants', ['merchant_id', 'ciudad'], unique=False)
    op.create_index(op.f('ix_merchant_variants_merchant_id'), 'merchant_variants', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_variants_nombre_raw'), 'merchant_variants', ['nombre_raw'], unique=True)
    op.create_table('subcategories',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único de la subcategoría'),
    sa.Column('category_id', sa.String(length=36), nullable=False, comment='ID de la categoría padre'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre de la subcategoría (ej: Transporte, Comida)'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment="Descripción y ejemplos (ej: 'Gasolina, seguro, lavados')"),
    sa.Column('icono', sa.String(length=10), nullable=False, comment='Emoji o icono para la subcategoría'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='Palabras clave separadas por coma para auto-categorización'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index('ix_subcategories_category_nombre', 'subcategories', ['category_id', 'nombre'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único del presupuesto'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil al que pertenece este presupuesto'),
    sa.Column('category_id', sa.String(length=36), nullable=False, comment='ID de la subcategoría presupuestada'),
    sa.Column('mes', sa.Date(), nullable=False, comment='Primer día del mes para este presupuesto (ej: 2025-11-01)'),
    sa.Column('amount_crc', sa.Numeric(precision=15, scale=2), nullable=False, comment='Límite de gasto en colones para esta categoría este mes'),
    sa.Column('monto_limite', sa.Numeric(precision=15, scale=2), nullable=False, comment='Alias de amount_crc para compatibilidad'),
    sa.Column('notas', sa.String(length=500), nullable=True, comment='Notas sobre este presupuesto'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del presupuesto'),
    sa.CheckConstraint('amount_crc > 0', name='check_budget_amount_positive'),
    sa.CheckConstraint('monto_limite > 0', name='check_budget_monto_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_created_at'), 'budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_budgets_mes'), 'budgets', ['mes'], unique=False)
    op.create_index(op.f('ix_budgets_profile_id'), 'budgets', ['profile_id'], unique=False)
    op.create_index('ix_budgets_profile_mes', 'budgets', ['profile_id', 'mes'], unique=False)
    op.create_index('ix_budgets_unique_category_month', 'budgets', ['profile_id', 'category_id', 'mes'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único de la transacción'),
    sa.Column('email_id', sa.String(length=255), nullable=False, comment='ID del correo de origen (para evitar duplicados)'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil al que pertenece esta transacción'),
    sa.Column('banco', sa.String(length=50), nullable=False, comment='Banco origen: bac o popular'),
    sa.Column('card_id', sa.String(length=36), nullable=True, comment='ID de la tarjeta usada en la transacción'),
    sa.Column('merchant_id', sa.String(length=36), nullable=True, comment='ID del comercio normalizado (ej: todas las variantes de Subway apuntan al mismo merchant)'),
    sa.Column('tipo_transaccion', sa.String(length=50), nullable=False, comment='Tipo: compra, transferencia, retiro, pago_servicio, etc.'),
    sa.Column('comercio', sa.String(length=255), nullable=False, comment='Nombre del comercio o destino de la transacción'),
    sa.Column('tipo_especial', sa.String(length=50), nullable=True, comment='Tipo especial: dinero_ajeno, intermediaria, transferencia_propia, etc.'),
    sa.Column('excluir_de_presupuesto', sa.Boolean(), nullable=False, comment='Si se debe excluir del cálculo de presupuesto (ej: alquiler intermediario)'),
    sa.Column('relacionada_con', sa.String(length=255), nullable=True, comment="Descripción de la relación (ej: 'Alquiler Nov-2025', 'Compra compartida con Juan')"),
    sa.Column('refund_transaction_id', sa.String(length=36), nullable=True, comment='ID de la transacción original si esto es un refund'),
    sa.Column('es_desconocida', sa.Boolean(), nullable=False, comment='Si la transacción no se reconoce o no se documentó bien'),
    sa.Column('confianza_categoria', sa.Integer(), nullable=False, comment='Nivel de confianza en la categorización (0-100)'),
    sa.Column('monto_original', sa.Numeric(precision=15, scale=2), nullable=False, comment='Monto en la moneda original'),
    sa.Column('moneda_original', sa.String(length=3), nullable=False, comment='Moneda original: USD o CRC'),
    sa.Column('monto_crc', sa.Numeric(precision=15, scale=2), nullable=False, comment='Monto convertido a colones (para unificar)'),
    sa.Column('tipo_cambio_usado', sa.Numeric(precision=10, scale=4), nullable=True, comment='Tipo de cambio usado si se hizo conversión USD→CRC'),
    sa.Column('fecha_transaccion', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la transacción'),
    sa.Column('ciudad', sa.String(length=100), nullable=True, comment='Ciudad donde se realizó la transacción'),
    sa.Column('pais', sa.String(length=100), nullable=True, comment='País donde se realizó la transacción'),
    sa.Column('subcategory_id', sa.String(length=36), nullable=True, comment='ID de la subcategoría asignada'),
    sa.Column('categoria_sugerida_por_ia', sa.String(length=100), nullable=True, comment='Subcategoría sugerida por Claude AI antes de confirmar'),
    sa.Column('necesita_revision', sa.Boolean(), nullable=False, comment='Si la transacción necesita revisión manual de categoría'),
    sa.Column('confirmada', sa.Boolean(), nullable=False, comment='Si la transacción está confirmada por el usuario'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales del usuario'),
    sa.Column('contexto', sa.Text(), nullable=True, comment="Contexto del gasto en lenguaje natural (ej: 'Compré carne con plata de mamá')"),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False, comment='Si la transacción fue detectada como anómala por ML'),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Score de anomalía (-1 a 1, donde < 0 es anómalo). Isolation Forest output.'),
    sa.Column('anomaly_reason', sa.String(length=255), nullable=True, comment="Razón de por qué se marcó como anómala (ej: 'Monto inusualmente alto')"),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint('confianza_categoria >= 0 AND confianza_categoria <= 100', name='check_transaction_confianza_valid'),
    sa.CheckConstraint('monto_crc > 0', name='check_transaction_monto_positive'),
    sa.CheckConstraint('monto_original > 0', name='check_transaction_original_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_banco'), 'transactions', ['banco'], unique=False)
    op.create_index(op.f('ix_transactions_card_id'), 'transactions', ['card_id'], unique=False)
    op.create_index('ix_transactions_comercio', 'transactions', ['comercio'], unique=False)
    op.create_index(op.f('ix_transactions_confirmada'), 'transactions', ['confirmada'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_deleted_at'), 'transactions', ['deleted_at'], unique=False)
    op.create_index('ix_transactions_desconocidas', 'transactions', ['es_desconocida'], unique=False)
    op.create_index(op.f('ix_transactions_email_id'), 'transactions', ['email_id'], unique=True)
    op.create_index(op.f('ix_transactions_es_desconocida'), 'transactions', ['es_desconocida'], unique=False)
    op.create_index(op.f('ix_transactions_excluir_de_presupuesto'), 'transactions', ['excluir_de_presupuesto'], unique=False)
    op.create_index(op.f('ix_transactions_fecha_transaccion'), 'transactions', ['fecha_transaccion'], unique=False)
    op.create_index(op.f('ix_transactions_is_anomaly'), 'transactions', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_monto_crc'), 'transactions', ['monto_crc'], unique=False)
    op.create_index(op.f('ix_transactions_necesita_revision'), 'transactions', ['necesita_revision'], unique=False)
    op.create_index('ix_transactions_profile_categoria', 'transactions', ['profile_id', 'subcategory_id'], unique=False)
    op.create_index('ix_transactions_profile_fecha', 'transactions', ['profile_id', 'fecha_transaccion'], unique=False)
    op.create_index(op.f('ix_transactions_profile_id'), 'transactions', ['profile_id'], unique=False)
    op.create_index('ix_transactions_profile_tipo', 'transactions', ['profile_id', 'tipo_transaccion'], unique=False)
    op.create_index(op.f('ix_transactions_refund_transaction_id'), 'transactions', ['refund_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_subcategory_id'), 'transactions', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_transactions_tipo_especial'), 'transactions', ['tipo_especial'], unique=False)
    op.create_index(op.f('ix_transactions_tipo_transaccion'), 'transactions', ['tipo_transaccion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_tipo_transaccion'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tipo_especial'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_subcategory_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_refund_transaction_id'), table_name='transactions')
    op.drop_index('ix_transactions_profile_tipo', table_name='transactions')
    op.drop_index(op.f('ix_transactions_profile_id'), table_name='transactions')
    op.drop_index('ix_transactions_profile_fecha', table_name='transactions')
    op.drop_index('ix_transactions_profile_categoria', table_name='transactions')
    op.drop_index(op.f('ix_transactions_necesita_revision'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_monto_crc'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_anomaly'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fecha_transaccion'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_excluir_de_presupuesto'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_es_desconocida'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_email_id'), table_name='transactions')
    op.drop_index('ix_transactions_desconocidas', table_name='transactions')
    op.drop_index(op.f('ix_transactions_deleted_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_confirmada'), table_name='transactions')
    op.drop_index('ix_transactions_comercio', table_name='transactions')
    op.drop_index(op.f('ix_transactions_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_banco'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_budgets_unique_category_month', table_name='budgets')
    op.drop_index('ix_budgets_profile_mes', table_name='budgets')
    op.drop_index(op.f('ix_budgets_profile_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_mes'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_created_at'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_subcategories_category_nombre', table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_merchant_variants_nombre_raw'), table_name='merchant_variants')
    op.drop_index(op.f('ix_merchant_variants_merchant_id'), table_name='merchant_variants')
    op.drop_index('ix_merchant_variants_merchant_ciudad', table_name='merchant_variants')
    op.drop_table('merchant_variants')
    op.drop_index(op.f('ix_incomes_tipo_especial'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_tipo'), table_name='incomes')
    op.drop_index('ix_incomes_profile_tipo', table_name='incomes')
    op.drop_index(op.f('ix_incomes_profile_id'), table_name='incomes')
    op.drop_index('ix_incomes_profile_fecha', table_name='incomes')
    op.drop_index(op.f('ix_incomes_monto_crc'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_fecha'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_excluir_de_presupuesto'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_es_recurrente'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_email_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_deleted_at'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_confirmado'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_cards_tipo'), table_name='cards')
    op.drop_index('ix_cards_profile_tipo', table_name='cards')
    op.drop_index(op.f('ix_cards_profile_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_deleted_at'), table_name='cards')
    op.drop_index(op.f('ix_cards_activa'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_profiles_es_activo'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email_outlook'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_merchants_nombre_normalizado'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_categoria_principal'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('exchange_rate_cache')
    op.drop_index(op.f('ix_categories_tipo'), table_name='categories')
    op.drop_index(op.f('ix_categories_nombre'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
