"""Initial schema with all models

Esta es la migración baseline que marca el estado actual de la base de datos.
Como la DB ya existía antes de inicializar Alembic, esta migración está vacía
pero establece el punto de partida para futuras migraciones.

Modelos incluidos:
- Profile: Sistema multi-perfil (Personal, Business, Familia)
- Budget: Presupuestos con historial y regla 50/30/20
- Category: Categorías principales (Necessities, Wants, Savings)
- Subcategory: Subcategorías granulares con keywords
- Card: Tarjetas débito/crédito con límites
- Transaction: Transacciones bancarias con categorización IA
- Income: Ingresos (recurrentes y únicos)

Revision ID: 2ebba5c4f9b2
Revises:
Create Date: 2025-11-18 22:42:25.250245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebba5c4f9b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
