"""add_patrimonio_models

Revision ID: 3ac35fbeb15b
Revises: ded1ba313883
Create Date: 2025-12-01 20:27:34.588431

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3ac35fbeb15b'
down_revision: str | Sequence[str] | None = 'ded1ba313883'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de esta cuenta'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo (ej: Cuenta corriente BAC)'),
    sa.Column('banco', sa.String(length=20), nullable=False, comment='Banco de la cuenta'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo de cuenta'),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True, comment='Últimos 4 dígitos del número de cuenta'),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False, comment='Saldo actual de la cuenta'),
    sa.Column('moneda', sa.String(length=3), nullable=False, comment='Moneda de la cuenta'),
    sa.Column('saldo_actualizado_at', sa.DateTime(timezone=True), nullable=False, comment='Última vez que se actualizó el saldo'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('activa', sa.Boolean(), nullable=False, comment='Si la cuenta está activa'),
    sa.Column('incluir_en_patrimonio', sa.Boolean(), nullable=False, comment='Si se incluye en el cálculo de patrimonio'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_activa'), 'accounts', ['activa'], unique=False)
    op.create_index(op.f('ix_accounts_profile_id'), 'accounts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de esta meta'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre de la meta (ej: Mundial 2026)'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción detallada de la meta'),
    sa.Column('icono', sa.String(length=10), nullable=True, comment='Emoji/icono de la meta'),
    sa.Column('monto_objetivo', sa.Numeric(precision=14, scale=2), nullable=False, comment='Monto objetivo a alcanzar'),
    sa.Column('monto_actual', sa.Numeric(precision=14, scale=2), nullable=False, comment='Monto actualmente ahorrado para esta meta'),
    sa.Column('moneda', sa.String(length=3), nullable=False, comment='Moneda de la meta'),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True, comment='Fecha objetivo para completar la meta'),
    sa.Column('fecha_completada', sa.Date(), nullable=True, comment='Fecha en que se completó la meta'),
    sa.Column('prioridad', sa.String(length=20), nullable=False, comment='Prioridad (alta, media, baja)'),
    sa.Column('estado', sa.String(length=20), nullable=False, comment='Estado de la meta'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_profile_id'), 'goals', ['profile_id'], unique=False)
    op.create_index(op.f('ix_goals_tenant_id'), 'goals', ['tenant_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de esta inversión'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo (ej: CDP 6 meses BAC)'),
    sa.Column('tipo', sa.String(length=30), nullable=False, comment='Tipo de inversión'),
    sa.Column('institucion', sa.String(length=100), nullable=False, comment='Institución donde está la inversión'),
    sa.Column('monto_principal', sa.Numeric(precision=14, scale=2), nullable=False, comment='Monto inicial invertido'),
    sa.Column('moneda', sa.String(length=3), nullable=False, comment='Moneda de la inversión'),
    sa.Column('tasa_interes_anual', sa.Numeric(precision=6, scale=4), nullable=False, comment='Tasa de interés anual (ej: 0.0373 = 3.73%)'),
    sa.Column('rendimiento_acumulado', sa.Numeric(precision=14, scale=2), nullable=False, comment='Rendimiento acumulado hasta la fecha'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha de inicio de la inversión'),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True, comment='Fecha de vencimiento (None si no aplica)'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('activa', sa.Boolean(), nullable=False, comment='Si la inversión está activa'),
    sa.Column('incluir_en_patrimonio', sa.Boolean(), nullable=False, comment='Si se incluye en el cálculo de patrimonio'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_activa'), 'investments', ['activa'], unique=False)
    op.create_index(op.f('ix_investments_profile_id'), 'investments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_investments_tenant_id'), 'investments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_tenant_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_profile_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_activa'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_goals_tenant_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_profile_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_profile_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_activa'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
