"""add_fk_to_patrimonio_and_reconciliation

Revision ID: 564c3e57cf7d
Revises: d2914ec36654
Create Date: 2025-12-04 06:18:32.299841

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '564c3e57cf7d'
down_revision: str | Sequence[str] | None = 'd2914ec36654'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'patrimonio_snapshots', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reconciliation_reports', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reconciliation_reports', type_='foreignkey')
    op.drop_constraint(None, 'patrimonio_snapshots', type_='foreignkey')
    # ### end Alembic commands ###
