"""add_sync_metadata_to_profile

Revision ID: 88802a30080f
Revises: e9cec578b152
Create Date: 2025-12-07 08:53:45.679687

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '88802a30080f'
down_revision: str | Sequence[str] | None = 'e9cec578b152'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema - add sync metadata to profiles."""
    op.add_column('profiles', sa.Column('last_statement_date', sa.Date(), nullable=True, comment='Fecha del último estado de cuenta procesado'))
    op.add_column('profiles', sa.Column('last_sync_date', sa.Date(), nullable=True, comment='Fecha de la última sincronización exitosa'))
    op.add_column('profiles', sa.Column('statement_cycle_days', sa.Integer(), nullable=True, comment='Días del ciclo de estado de cuenta (detectado automáticamente)'))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('profiles', 'statement_cycle_days')
    op.drop_column('profiles', 'last_sync_date')
    op.drop_column('profiles', 'last_statement_date')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_merchant_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_merchant_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_merchant_preferences', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Origen: user_correction, auto_detected')
    op.alter_column('user_merchant_preferences', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_comment='Confianza de 0.00 a 1.00')
    op.alter_column('user_merchant_preferences', 'times_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Veces que se ha usado esta preferencia')
    op.alter_column('user_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_contacts', 'total_amount_crc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('user_contacts', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_contacts', 'sinpe_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nombre como aparece en SINPE',
               existing_comment='Nombre como aparece en SINPE (ej: ROSA MARIA CRUZ)',
               existing_nullable=True)
    op.add_column('transactions', sa.Column('categoria_original_ia', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Categoría original sugerida por IA antes de corrección'))
    op.alter_column('transactions', 'necesita_reconciliacion_sinpe',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='True si es un SINPE/transferencia con descripción ambigua que necesita aclaración',
               existing_server_default=sa.text('false'))
    op.alter_column('transaction_embeddings', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Modelo usado: voyage-3-lite, text-embedding-3-small, etc.',
               existing_comment='Modelo usado: all-MiniLM-L6-v2, voyage-3-lite, etc.',
               existing_nullable=False)
    op.alter_column('transaction_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               comment='Vector embedding para búsqueda semántica',
               existing_comment='Vector embedding para búsqueda semántica (384 dims)',
               existing_nullable=False)
    op.drop_column('profiles', 'statement_cycle_days')
    op.drop_column('profiles', 'last_sync_date')
    op.drop_column('profiles', 'last_statement_date')
    op.alter_column('global_merchant_suggestions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_merchant_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_merchant_suggestions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='Estado: pending, approved, rejected')
    op.alter_column('global_merchant_suggestions', 'user_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Número de usuarios que sugirieron esto')
    # ### end Alembic commands ###
