"""add_es_tentativa_to_transactions

Revision ID: 8e1de369a884
Revises: e9c12d4be588
Create Date: 2025-12-04 18:51:33.852559

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8e1de369a884'
down_revision: str | Sequence[str] | None = 'e9c12d4be588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Agregar columna con server_default para las filas existentes
    op.add_column(
        'transactions',
        sa.Column(
            'es_tentativa',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),  # Las transacciones existentes NO son tentativas
            comment='True si se importó sin estado de cuenta base (pendiente de reconciliación)'
        )
    )
    op.create_index(op.f('ix_transactions_es_tentativa'), 'transactions', ['es_tentativa'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_es_tentativa'), table_name='transactions')
    op.drop_column('transactions', 'es_tentativa')
    # ### end Alembic commands ###
