"""Add unique constraint to Profile.email_outlook

Revision ID: a052c6fc5837
Revises: 2ebba5c4f9b2
Create Date: 2025-11-18 22:46:51.366532

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a052c6fc5837'
down_revision: str | Sequence[str] | None = '2ebba5c4f9b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_email_outlook'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email_outlook'), 'profiles', ['email_outlook'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_email_outlook'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email_outlook'), 'profiles', ['email_outlook'], unique=False)
    # ### end Alembic commands ###
