"""Add reconciliation and patrimonio tracking fields

Revision ID: d2914ec36654
Revises: e69daeb1e3e7
Create Date: 2025-12-03 23:26:57.627353

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd2914ec36654'
down_revision: str | Sequence[str] | None = 'e69daeb1e3e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrimonio_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único del snapshot'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de este snapshot'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('fecha_snapshot', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora del snapshot'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo: manual, automatico, onboarding, reconciliacion'),
    sa.Column('saldo_cuentas_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total en cuentas bancarias (colones)'),
    sa.Column('saldo_cuentas_usd', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total en cuentas bancarias (dólares)'),
    sa.Column('saldo_inversiones_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total en inversiones (colones)'),
    sa.Column('saldo_inversiones_usd', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total en inversiones (dólares)'),
    sa.Column('deuda_tarjetas_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Deuda total en tarjetas de crédito (colones)'),
    sa.Column('deuda_tarjetas_usd', sa.Numeric(precision=14, scale=2), nullable=False, comment='Deuda total en tarjetas de crédito (dólares)'),
    sa.Column('deuda_prestamos_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Deuda en préstamos (colones)'),
    sa.Column('deuda_prestamos_usd', sa.Numeric(precision=14, scale=2), nullable=False, comment='Deuda en préstamos (dólares)'),
    sa.Column('tipo_cambio_usd', sa.Numeric(precision=8, scale=2), nullable=False, comment='Tipo de cambio USD/CRC usado para este snapshot'),
    sa.Column('total_activos_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total de activos en colones (cuentas + inversiones)'),
    sa.Column('total_deudas_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total de deudas en colones (tarjetas + préstamos)'),
    sa.Column('patrimonio_neto_crc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Patrimonio neto en colones (activos - deudas)'),
    sa.Column('cambio_vs_anterior', sa.Numeric(precision=14, scale=2), nullable=True, comment='Cambio en patrimonio vs snapshot anterior (puede ser negativo)'),
    sa.Column('cambio_porcentual', sa.Numeric(precision=6, scale=2), nullable=True, comment='Cambio porcentual vs snapshot anterior'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas opcionales del usuario'),
    sa.Column('detalles_json', sa.Text(), nullable=True, comment='JSON con desglose detallado por cuenta/tarjeta'),
    sa.Column('es_fecha_base', sa.Boolean(), nullable=False, comment='True si es el snapshot de FECHA_BASE (inicio de tracking)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Cuándo se creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patrimonio_fecha_base', 'patrimonio_snapshots', ['profile_id', 'es_fecha_base'], unique=False)
    op.create_index('ix_patrimonio_profile_fecha', 'patrimonio_snapshots', ['profile_id', 'fecha_snapshot'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_created_at'), 'patrimonio_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_deleted_at'), 'patrimonio_snapshots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_es_fecha_base'), 'patrimonio_snapshots', ['es_fecha_base'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_fecha_snapshot'), 'patrimonio_snapshots', ['fecha_snapshot'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_profile_id'), 'patrimonio_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_patrimonio_snapshots_tenant_id'), 'patrimonio_snapshots', ['tenant_id'], unique=False)
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único del reporte'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de este reporte'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('banco', sa.String(length=20), nullable=False, comment='Banco del estado de cuenta'),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=False, comment='Fecha de inicio del período (ej: 01-Nov-2024)'),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=False, comment='Fecha de fin del período (ej: 30-Nov-2024)'),
    sa.Column('es_tarjeta_credito', sa.Boolean(), nullable=False, comment='True si es estado de tarjeta de crédito, False si es cuenta corriente'),
    sa.Column('card_id', sa.String(length=36), nullable=True, comment='ID de la tarjeta de crédito (si aplica)'),
    sa.Column('account_id', sa.String(length=36), nullable=True, comment='ID de la cuenta bancaria (si aplica)'),
    sa.Column('total_estado_cuenta', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total de transacciones según el PDF del banco'),
    sa.Column('total_importado', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total de transacciones importadas al sistema'),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=False, comment='Diferencia entre estado de cuenta e importado'),
    sa.Column('transacciones_estado_cuenta', sa.Integer(), nullable=False, comment='Número de transacciones en el PDF'),
    sa.Column('transacciones_importadas', sa.Integer(), nullable=False, comment='Número de transacciones importadas'),
    sa.Column('transacciones_matched', sa.Integer(), nullable=False, comment='Transacciones que coinciden exactamente'),
    sa.Column('transacciones_discrepantes', sa.Integer(), nullable=False, comment='Transacciones con diferencias de monto'),
    sa.Column('transacciones_faltantes', sa.Integer(), nullable=False, comment='Transacciones en PDF pero no importadas'),
    sa.Column('transacciones_huerfanas', sa.Integer(), nullable=False, comment='Transacciones importadas pero no en PDF'),
    sa.Column('estado', sa.String(length=20), nullable=False, comment='Estado: pendiente, en_proceso, completada, fallida'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas del usuario sobre la reconciliación'),
    sa.Column('detalles_json', sa.Text(), nullable=True, comment='JSON con detalles de matches, discrepancias, etc.'),
    sa.Column('pdf_email_id', sa.String(length=255), nullable=True, comment='ID del email del cual se extrajo el PDF'),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True, comment='Nombre del archivo PDF procesado'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Cuándo se creó el reporte'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última actualización'),
    sa.Column('completado_at', sa.DateTime(timezone=True), nullable=True, comment='Cuándo se completó la reconciliación'),
    sa.CheckConstraint('periodo_inicio < periodo_fin', name='check_reconciliation_periodo_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_profile_banco', 'reconciliation_reports', ['profile_id', 'banco'], unique=False)
    op.create_index('ix_reconciliation_profile_periodo', 'reconciliation_reports', ['profile_id', 'periodo_inicio', 'periodo_fin'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_account_id'), 'reconciliation_reports', ['account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_card_id'), 'reconciliation_reports', ['card_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_created_at'), 'reconciliation_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_deleted_at'), 'reconciliation_reports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_estado'), 'reconciliation_reports', ['estado'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_profile_id'), 'reconciliation_reports', ['profile_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_tenant_id'), 'reconciliation_reports', ['tenant_id'], unique=False)
    op.add_column('transactions', sa.Column('estado', sa.String(length=20), nullable=False, comment='Estado: pendiente, confirmada, reconciliada, cancelada, huerfana'))
    op.add_column('transactions', sa.Column('es_historica', sa.Boolean(), nullable=False, comment='True si es anterior a FECHA_BASE (no cuenta para patrimonio activo)'))
    op.add_column('transactions', sa.Column('fecha_registro_sistema', sa.DateTime(timezone=True), nullable=False, comment='Cuándo se importó al sistema (puede diferir de created_at si hubo migración)'))
    op.add_column('transactions', sa.Column('reconciliacion_id', sa.String(length=36), nullable=True, comment='ID del reporte de reconciliación que verificó esta transacción'))
    op.add_column('transactions', sa.Column('reconciliada_en', sa.DateTime(timezone=True), nullable=True, comment='Cuándo fue reconciliada'))
    op.add_column('transactions', sa.Column('es_transferencia_interna', sa.Boolean(), nullable=False, comment='True si es transferencia entre cuentas propias (no afecta patrimonio neto)'))
    op.add_column('transactions', sa.Column('cuenta_origen_id', sa.String(length=36), nullable=True, comment='Cuenta de origen para transferencias internas'))
    op.add_column('transactions', sa.Column('cuenta_destino_id', sa.String(length=36), nullable=True, comment='Cuenta de destino para transferencias internas'))
    op.add_column('transactions', sa.Column('monto_original_estimado', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monto original si hubo discrepancia con el estado de cuenta'))
    op.add_column('transactions', sa.Column('monto_ajustado', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monto corregido tras reconciliación'))
    op.add_column('transactions', sa.Column('razon_ajuste', sa.String(length=500), nullable=True, comment="Explicación del ajuste (ej: 'Propina añadida', 'Tipo de cambio diferente')"))
    op.add_column('transactions', sa.Column('referencia_banco', sa.String(length=50), nullable=True, comment='Número de referencia del banco para matching exacto en reconciliación'))
    op.create_index(op.f('ix_transactions_es_historica'), 'transactions', ['es_historica'], unique=False)
    op.create_index(op.f('ix_transactions_es_transferencia_interna'), 'transactions', ['es_transferencia_interna'], unique=False)
    op.create_index(op.f('ix_transactions_estado'), 'transactions', ['estado'], unique=False)
    op.create_index(op.f('ix_transactions_fecha_registro_sistema'), 'transactions', ['fecha_registro_sistema'], unique=False)
    op.create_index('ix_transactions_profile_estado', 'transactions', ['profile_id', 'estado'], unique=False)
    op.create_index('ix_transactions_profile_historica', 'transactions', ['profile_id', 'es_historica'], unique=False)
    op.create_index('ix_transactions_reconciliacion', 'transactions', ['reconciliacion_id'], unique=False)
    op.create_index(op.f('ix_transactions_reconciliacion_id'), 'transactions', ['reconciliacion_id'], unique=False)
    op.create_index('ix_transactions_referencia_banco', 'transactions', ['referencia_banco'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['cuenta_origen_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'reconciliation_reports', ['reconciliacion_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'accounts', ['cuenta_destino_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_referencia_banco', table_name='transactions')
    op.drop_index(op.f('ix_transactions_reconciliacion_id'), table_name='transactions')
    op.drop_index('ix_transactions_reconciliacion', table_name='transactions')
    op.drop_index('ix_transactions_profile_historica', table_name='transactions')
    op.drop_index('ix_transactions_profile_estado', table_name='transactions')
    op.drop_index(op.f('ix_transactions_fecha_registro_sistema'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_estado'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_es_transferencia_interna'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_es_historica'), table_name='transactions')
    op.drop_column('transactions', 'referencia_banco')
    op.drop_column('transactions', 'razon_ajuste')
    op.drop_column('transactions', 'monto_ajustado')
    op.drop_column('transactions', 'monto_original_estimado')
    op.drop_column('transactions', 'cuenta_destino_id')
    op.drop_column('transactions', 'cuenta_origen_id')
    op.drop_column('transactions', 'es_transferencia_interna')
    op.drop_column('transactions', 'reconciliada_en')
    op.drop_column('transactions', 'reconciliacion_id')
    op.drop_column('transactions', 'fecha_registro_sistema')
    op.drop_column('transactions', 'es_historica')
    op.drop_column('transactions', 'estado')
    op.drop_index(op.f('ix_reconciliation_reports_tenant_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_profile_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_estado'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_deleted_at'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_created_at'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_card_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_account_id'), table_name='reconciliation_reports')
    op.drop_index('ix_reconciliation_profile_periodo', table_name='reconciliation_reports')
    op.drop_index('ix_reconciliation_profile_banco', table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.drop_index(op.f('ix_patrimonio_snapshots_tenant_id'), table_name='patrimonio_snapshots')
    op.drop_index(op.f('ix_patrimonio_snapshots_profile_id'), table_name='patrimonio_snapshots')
    op.drop_index(op.f('ix_patrimonio_snapshots_fecha_snapshot'), table_name='patrimonio_snapshots')
    op.drop_index(op.f('ix_patrimonio_snapshots_es_fecha_base'), table_name='patrimonio_snapshots')
    op.drop_index(op.f('ix_patrimonio_snapshots_deleted_at'), table_name='patrimonio_snapshots')
    op.drop_index(op.f('ix_patrimonio_snapshots_created_at'), table_name='patrimonio_snapshots')
    op.drop_index('ix_patrimonio_profile_fecha', table_name='patrimonio_snapshots')
    op.drop_index('ix_patrimonio_fecha_base', table_name='patrimonio_snapshots')
    op.drop_table('patrimonio_snapshots')
    # ### end Alembic commands ###
