"""add_users_table

Revision ID: ded1ba313883
Revises: 91d86299896d
Create Date: 2025-12-01 19:09:19.256809

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ded1ba313883'
down_revision: str | Sequence[str] | None = '91d86299896d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email para login (único)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt del password'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del usuario'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si el usuario está activo'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Si el email está verificado'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última actualización'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Último login exitoso'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación (soft delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.alter_column('merchants', 'categorias_posibles',
               existing_type=sa.TEXT(),
               comment='Lista de categorías posibles para comercios ambiguos (JSON serializado)',
               existing_comment='Lista de categorías posibles en formato JSON (ej: ["Supermercado", "Electrónica"])',
               existing_nullable=True)
    op.alter_column('transaction_embeddings', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Modelo usado: voyage-3-lite, text-embedding-3-small, etc.',
               existing_comment='Modelo usado: voyage-3-lite, text-embedding-3-small, all-MiniLM-L6-v2',
               existing_nullable=False)
    op.alter_column('transaction_embeddings', 'embedding_dim',
               existing_type=sa.INTEGER(),
               comment='Dimensión del vector',
               existing_comment='Dimensión del vector (384 para MiniLM, 1024 para Voyage, 1536 para OpenAI)',
               existing_nullable=False,
               existing_server_default=sa.text('384'))
    op.drop_index(op.f('idx_embedding_hnsw'), table_name='transaction_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('transaction_embeddings_transaction_id_key'), 'transaction_embeddings', type_='unique')
    op.drop_index(op.f('ix_transaction_embeddings_transaction_id'), table_name='transaction_embeddings')
    op.create_index(op.f('ix_transaction_embeddings_transaction_id'), 'transaction_embeddings', ['transaction_id'], unique=True)
    op.alter_column('transactions', 'es_comercio_ambiguo',
               existing_type=sa.BOOLEAN(),
               comment='True si el comercio puede tener múltiples categorías (ej: Walmart)',
               existing_comment='True si la transacción es de un comercio ambiguo que requiere confirmación',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'es_comercio_ambiguo',
               existing_type=sa.BOOLEAN(),
               comment='True si la transacción es de un comercio ambiguo que requiere confirmación',
               existing_comment='True si el comercio puede tener múltiples categorías (ej: Walmart)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_transaction_embeddings_transaction_id'), table_name='transaction_embeddings')
    op.create_index(op.f('ix_transaction_embeddings_transaction_id'), 'transaction_embeddings', ['transaction_id'], unique=False)
    op.create_unique_constraint(op.f('transaction_embeddings_transaction_id_key'), 'transaction_embeddings', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_embedding_hnsw'), 'transaction_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('transaction_embeddings', 'embedding_dim',
               existing_type=sa.INTEGER(),
               comment='Dimensión del vector (384 para MiniLM, 1024 para Voyage, 1536 para OpenAI)',
               existing_comment='Dimensión del vector',
               existing_nullable=False,
               existing_server_default=sa.text('384'))
    op.alter_column('transaction_embeddings', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Modelo usado: voyage-3-lite, text-embedding-3-small, all-MiniLM-L6-v2',
               existing_comment='Modelo usado: voyage-3-lite, text-embedding-3-small, etc.',
               existing_nullable=False)
    op.alter_column('merchants', 'categorias_posibles',
               existing_type=sa.TEXT(),
               comment='Lista de categorías posibles en formato JSON (ej: ["Supermercado", "Electrónica"])',
               existing_comment='Lista de categorías posibles para comercios ambiguos (JSON serializado)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
