"""add_billing_cycles_and_card_payments

Revision ID: e69daeb1e3e7
Revises: 3ac35fbeb15b
Create Date: 2025-12-01 21:26:12.818453

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e69daeb1e3e7'
down_revision: str | Sequence[str] | None = '3ac35fbeb15b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('card_id', sa.String(length=36), nullable=False, comment='ID de la tarjeta a la que pertenece este ciclo'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha de inicio del período (día después del corte anterior)'),
    sa.Column('fecha_corte', sa.Date(), nullable=False, comment='Fecha de corte del período'),
    sa.Column('fecha_pago', sa.Date(), nullable=False, comment='Fecha límite de pago para evitar intereses'),
    sa.Column('total_periodo', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total gastado en este período'),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False, comment='Saldo arrastrado del período anterior (si no se pagó total)'),
    sa.Column('intereses_periodo', sa.Numeric(precision=14, scale=2), nullable=False, comment='Intereses cobrados por saldo anterior'),
    sa.Column('total_a_pagar', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total a pagar (periodo + anterior + intereses)'),
    sa.Column('pago_minimo', sa.Numeric(precision=14, scale=2), nullable=False, comment='Pago mínimo requerido'),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total pagado en este ciclo'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: abierto, cerrado, pagado, parcial, vencido'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_cycles_card_id'), 'billing_cycles', ['card_id'], unique=False)
    op.create_index(op.f('ix_billing_cycles_status'), 'billing_cycles', ['status'], unique=False)
    op.create_index(op.f('ix_billing_cycles_tenant_id'), 'billing_cycles', ['tenant_id'], unique=False)
    op.create_table('card_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('billing_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['billing_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_payments_billing_cycle_id'), 'card_payments', ['billing_cycle_id'], unique=False)
    op.create_index(op.f('ix_card_payments_card_id'), 'card_payments', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_payments_tenant_id'), 'card_payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_payments_tenant_id'), table_name='card_payments')
    op.drop_index(op.f('ix_card_payments_card_id'), table_name='card_payments')
    op.drop_index(op.f('ix_card_payments_billing_cycle_id'), table_name='card_payments')
    op.drop_table('card_payments')
    op.drop_index(op.f('ix_billing_cycles_tenant_id'), table_name='billing_cycles')
    op.drop_index(op.f('ix_billing_cycles_status'), table_name='billing_cycles')
    op.drop_index(op.f('ix_billing_cycles_card_id'), table_name='billing_cycles')
    op.drop_table('billing_cycles')
    # ### end Alembic commands ###
