"""add_pending_questions_table

Revision ID: e9c12d4be588
Revises: 564c3e57cf7d
Create Date: 2025-12-04 18:46:59.927158

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e9c12d4be588'
down_revision: str | Sequence[str] | None = '564c3e57cf7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_questions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID único de la pregunta'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='ID del tenant para multi-tenancy (futuro)'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='ID del perfil dueño de esta pregunta'),
    sa.Column('transaction_id', sa.String(length=36), nullable=True, comment='ID de la transacción relacionada (si aplica)'),
    sa.Column('tipo', sa.String(length=30), nullable=False, comment='Tipo de pregunta'),
    sa.Column('prioridad', sa.String(length=10), nullable=False, comment='Prioridad de la pregunta'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado de la pregunta'),
    sa.Column('pregunta', sa.Text(), nullable=False, comment='Texto de la pregunta para mostrar al usuario'),
    sa.Column('contexto', sa.Text(), nullable=True, comment='Contexto adicional (JSON con datos relevantes)'),
    sa.Column('opciones', sa.Text(), nullable=True, comment='Opciones de respuesta en formato JSON array'),
    sa.Column('monto_relacionado', sa.Numeric(precision=14, scale=2), nullable=True, comment='Monto de la transacción relacionada'),
    sa.Column('respuesta', sa.Text(), nullable=True, comment='Respuesta del usuario'),
    sa.Column('respondida_en', sa.DateTime(timezone=True), nullable=True, comment='Fecha/hora en que se respondió'),
    sa.Column('origen', sa.String(length=30), nullable=False, comment='De dónde vino: onboarding, reconciliacion, sync_diario'),
    sa.Column('orden', sa.Integer(), nullable=False, comment='Orden para mostrar (menor = primero)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_questions_profile_id'), 'pending_questions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_pending_questions_status'), 'pending_questions', ['status'], unique=False)
    op.create_index(op.f('ix_pending_questions_tenant_id'), 'pending_questions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pending_questions_transaction_id'), 'pending_questions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_questions_transaction_id'), table_name='pending_questions')
    op.drop_index(op.f('ix_pending_questions_tenant_id'), table_name='pending_questions')
    op.drop_index(op.f('ix_pending_questions_status'), table_name='pending_questions')
    op.drop_index(op.f('ix_pending_questions_profile_id'), table_name='pending_questions')
    op.drop_table('pending_questions')
    # ### end Alembic commands ###
